language: scala
scala: 2.12.4 # this needs to be in sync with Scala version used in .appveyor.yml
jdk: oraclejdk8
dist: trusty
sudo: required

services:
  - docker

stages:
  - name: clean
    if: NOT type = pull_request
  - name: compile
  - name: unit test
  - name: test
  - name: publish
    # weirdly, we have to add the extra PR check
    if: NOT type = pull_request

# this all goes in the test stage
env:
  matrix:
    # - CONNECTOR=couchbase
    - CONNECTOR=marklogic_json
    - CONNECTOR=marklogic_xml
    - CONNECTOR=mimir
    - CONNECTOR=mongodb_3_2
    - CONNECTOR=mongodb_3_4
    - CONNECTOR=mongodb_read_only
    # - CONNECTOR=spark_local_test # no spark for 2.12
    # - CONNECTOR=spark_hdfs # no spark for 2.12
  global:
    - COURSIER_PROGRESS=0

# this is also the test stage :eyeroll:
script:
  - set -e

  # travis installs postgres by default this will stop and free up the psql port
  # needed by the  postgreql container
  - sudo /etc/init.d/postgresql stop
  - sudo /etc/init.d/mysql stop
  - sudo service memcached stop

  - docker/scripts/setupContainers -u quasar_metastore
  - docker/scripts/setupContainers -u quasar_$CONNECTOR
  - docker ps

  # populate the it/testing.conf file
  - docker/scripts/assembleTestingConf -c quasar_metastore
  - docker/scripts/assembleTestingConf -i quasar_$CONNECTOR
  - cat it/testing.conf

  - |-
    SPECIFIC_DELEGATE=

    case $CONNECTOR in
      couchbase) SPECIFIC_DELEGATE="couchbaseIt/testOnly -- xonly failtrace" ;;
      marklogic_*) SPECIFIC_DELEGATE="marklogicIt/testOnly -- xonly failtrace" ;;
      mongodb_*) SPECIFIC_DELEGATE="mongoIt/testOnly -- xonly failtrace" ;;

      spark_hdfs)

        ./sbt -DisIsolatedEnv=${ISOLATED_ENV:=false} ++$TRAVIS_SCALA_VERSION \
          'set every assemblyJarName in assembly := "sparkcore.jar"' \
          'set every sparkDependencyProvided := true' \
          sparkcore/assembly

        cp ./.targets/sparkcore/scala-2.11/sparkcore.jar $TRAVIS_BUILD_DIR

        export SPARKCORE_JAR_PATH="$TRAVIS_BUILD_DIR/sparkcore.jar"

        ;;

      *) ;;
    esac

  # workaround for the fact that travis caching isn't working. when it starts working again, remove this
  - travis_wait 40 ./sbt -DisIsolatedEnv=${ISOLATED_ENV:=false} ++$TRAVIS_SCALA_VERSION connector/test:compile

  # then run the tests (note that this re-runs some tests; we can get rid of that once we have polyrepo)
  - |-
    ./sbt -DisIsolatedEnv=${ISOLATED_ENV:=false} ++$TRAVIS_SCALA_VERSION \
      it/sideEffectTestFSConfig \
      "it/testOnly -- xonly failtrace" \
      "$SPECIFIC_DELEGATE"

  - set +e

jobs:
  include:
    - stage: clean
      env:
      script: ./sbt -DisIsolatedEnv=${ISOLATED_ENV:=false} clean

    - stage: compile
      env:
      script:
        - set -e

        - |-
          ./sbt -DisIsolatedEnv=${ISOLATED_ENV:=false} ++$TRAVIS_SCALA_VERSION \
            checkHeaders \
            test:compile

        - set +e

    # note that the "test" stage has special significance to Travis (it's the only matrix-able stage)
    - stage: unit test
      env:
      script:
        - |-
          ./sbt -DisIsolatedEnv=${ISOLATED_ENV:=false} ++$TRAVIS_SCALA_VERSION \
            it/sideEffectTestFSConfig \
            "testOnly -- xonly failtrace" \
            "exclusive:testOnly -- xonly failtrace"

    - stage: publish
      env:
      script:
        - set -e
        - './sbt -DisIsolatedEnv=${ISOLATED_ENV:=false} ++$TRAVIS_SCALA_VERSION doc web/assembly'
        - scripts/testJar

        # release to sonatype
        - scripts/quasarPublishAndTag

        # recreate sparkcore.jar, which is just going to hang out
        - |-
          ./sbt -DisIsolatedEnv=${ISOLATED_ENV:=false} ++$TRAVIS_SCALA_VERSION \
            'set every assemblyJarName in assembly := "sparkcore.jar"' \
            'set every sparkDependencyProvided := true' \
            sparkcore/assembly

        # release to github
        - scripts/publishJar

        - set +e

notifications:
  irc:
    template:
      - "%{result}: %{repository_slug}#%{build_number} (%{branch}@%{commit}: %{author})
        %{build_url}"
  slack:
    secure: k7tat0w0CSokOD1K0nfPhFY9Z3xkYHXboNlW1WgNAjqtq56hQsfQWhN8z6cXRAs/CgT8ME0K//wDN/HgdG91/aVh1smv/hxMa6P/o70GclhvUkB4iTis3kv9la3Kf2w3K5pbWJ6fFLdAZqc5i9XpQ8q+d7UTgwAxj1ZcYwaCSVo=

branches:
  only:
    - master
    - /^backport.*$/

cache:
  directories:
    - $HOME/.cache/quasar/fileDownloads
    - $HOME/.coursier/cache
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - target
    - .targets
    - project/project/target
    - project/target

before_cache:
  - find "$HOME/.sbt/" -name '*.lock' -print0 | xargs -0 rm
  - find "$HOME/.ivy2/" -name 'ivydata-*.properties' -print0 | xargs -0 rm
